### ISSUE TITLE
TypeError: 'NoneType' object is not iterable - line 75, in parse_ip

### ISSUE THREAD

**Issue by npormambi** [abhinavbom/Threat-Intelligence-Hunter#10]
Hello Abhinav,
I am getting below error when using the below cli
python tih.py -ip 52.203.115.53

TypeError: 'NoneType' object is not iterable - line 75, in parse_ip
Also not able to connect to emerging threat rules though i have properly provided the proxy addres

How can i sort it out

Thanks

**Comment by abhinavbom** [comment]
@npormambi  I just ran a search and it went fine for emergingthreats. Here is my output: 

> Abhinavs-MacBook-Pro:Threat-Intelligence-Hunter-master abhinavsingh$ python tih.py -ip 52.203.115.53
>  Threat Intelligence Hunter framework Begins now 
> Intel test
> Connecting with http://rules.emergingthreats.net/blockrules/compromised-ips.txt
> Connecting with https://zeustracker.abuse.ch/blocklist.php?download=ipblocklist
> Connecting with https://isc.sans.edu/ipsascii.html?limit=2000
> Connecting with http://www.nothink.org/blacklist/blacklist_ssh_all.txt
> Connecting with https://check.torproject.org/exit-addresses
> Connecting with http://www.openbl.org/lists/base.txt
> Connecting with http://www.malwaredomainlist.com/hostslist/ip.txt
> Connecting with http://www.ciarmy.com/list/ci-badguys.txt
> Connecting with http://doc.emergingthreats.net/pub/Main/RussianBusinessNetwork/emerging-rbn-malvertisers.txt
> Connecting with http://www.okean.com/korea.txt
> Connecting with http://talosintel.com/files/additional_resources/ips_blacklist/ip-filter.blf
> Connecting with https://www.dragonresearchgroup.org/insight/sshpwauth.txt
> Connecting with http://www.nothink.org/blacklist/blacklist_malware_dns.txt
> Connecting with http://www.nothink.org/blacklist/blacklist_malware_irc.txt
> Connecting with http://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
> Connecting with http://www.projecthoneypot.org/list_of_ips.php?rss=1
> Connecting with http://www.nothink.org/blacklist/blacklist_malware_http.txt
> Connecting with https://reputation.alienvault.com/reputation.generic
> Connecting with http://doc.emergingthreats.net/pub/Main/RussianBusinessNetwork/RussianBusinessNetworkIPs.txt
> Connecting with http://www.blocklist.de/lists/all.txt
> Connecting with http://malc0de.com/bl/IP_Blacklist.txt
> Connecting with http://www.badips.com/get/list/apache-wordpress/0?age=1000h
> Connecting with https://www.dragonresearchgroup.org/insight/vncprobe.txt
> Total scanned indicators 37093
> Connecting to Virustotal
> looking for IP 52.203.115.53


Did you provide the Virustotal API key to vt.py file ? 

This script also searches for your IP/domain on Virustotal which would require API key. Here is the snippet where you need to provide the key: 

> from lib.parse import *
> 
> #Add your public API key before starting.
> api = ''
> base = 'https://www.virustotal.com/vtapi/v2/'

**Comment by abhinavbom** [comment]
closing the issue. Please reopen if there are still issues.
