### ISSUE TITLE
/api/urlvoid.py single quote fix

### ISSUE THREAD

**Issue by DrunkBinary** [abhinavbom/Threat-Intelligence-Hunter#11]
In /api/urlvoid.py, line 15 needs to be corrected from api_key = ''+'/'  to "'+'/", as it current form will error out when the user inputs the API in the plus column, unless you meant for the user to put the api where the / was.

**Comment by abhinavbom** [comment]
@DrunkBinary  the idea is to get the api key ' ' and then append a slash '/' . So the URL would become /<API key>/..
I found another bug in the code while I was looking at this issue. I have changed the code.

**Comment by abhinavbom** [comment]
https://github.com/abhinavbom/Threat-Intelligence-Hunter/commit/5d9f2ef22c2f74895a3fcf5a1e7a7d417c52dc61
