### ISSUE TITLE
Parse error in tih.py

### ISSUE THREAD

**Issue by asingh270** [abhinavbom/Threat-Intelligence-Hunter#14]
Following blacklist is down. Crashes the program.
https://www.dragonresearchgroup.org/insight/sshpwauth.txt
Following error is caused: 

Connecting with https://www.dragonresearchgroup.org/insight/sshpwauth.txt
[!] Could not connect to: https://www.dragonresearchgroup.org/insight/sshpwauth.txt
Traceback (most recent call last):
  File "tih.py", line 62, in <module>
    main()
  File "tih.py", line 41, in main
    parse_ip(args.ip)
  File "/Users/abhinavsingh/Downloads/FileInsight-plugins-master/Threat-Intelligence-Hunter-master/lib/parse.py", line 75, in parse_ip
    for line in c:

**Comment by abhinavbom** [comment]
Seems like the feed is no longer available. Needs to be removed. I'll update the code. Meanwhile, you can comment out the feed from feeds.py and continue using the tool.

**Comment by abhinavbom** [comment]
done!
