### ISSUE TITLE
unable to search for multiple IPs in Virustotal

### ISSUE THREAD

**Issue by illiyeen** [abhinavbom/Threat-Intelligence-Hunter#8]
Only one IP is searched when multiple command line arguments are specified: 
Eg: 
`Connecting to Virustotal
looking for IP 222.186.21.20
Detected:  44 / 57`

**Comment by abhinavbom** [comment]
Thanks for the update. Will be fixing the bug soon.

**Comment by abhinavbom** [comment]
Fixed the issue in latest commit. Version upgraded.
