### ISSUE TITLE
Import error in the code. Change directories

### ISSUE THREAD

**Issue by goblet010** [abhinavbom/Threat-Intelligence-Hunter#9]
Following error pops up when the script is compiled. 

`Traceback (most recent call last):
  File "/Users/dds/github/Threat-Intelligence-Hunter/tih.py", line 5, in <module>
    from bin.md5vt import *
ImportError: No module named md5vt`

**Comment by abhinavbom** [comment]
I missed to rename the directories in the code. 
Fixing.

**Comment by abhinavbom** [comment]
fixed.
